---
image: quay.io/ansible/molecule:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker -v
  - python -V
  - ansible --version
  - molecule --version
  - pip install tox

test:
  script:
    - tox
